name: create_mongodb_user
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: Application Name (like 'hc-abc')
        required: true
      env_name:
        description: Environment Name (like 'dev, stage, prod')
        required: true
      db_name:
        description: Database Name (alphanumeric with _ only, casesensitive)
        required: true
      user_name:
        description: User Name (alphanumeric with _ only, casesensitive)
        required: true
      user_password:
        description: User Password (alphanumeric with upper, lower and !~-_ only, casesensitive)
        required: true
      user_role:
          description: User Role
          required: true 
          type: choice
          options:
            - readWrite
            - read
  push:
    branches:
      - develop
      - feature/*
    paths:
      - ".github/workflows/*mongodb*"
      - "scripts/mongodb_atlas/**"
          
jobs:
  workflow_dispatch:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Create MongoDB User Workflow
        run: |
          echo App Name ${{ github.event.inputs.app_name }}
          echo App Name ${{ github.event.inputs.user_name }}
          echo App Name ${{ github.event.inputs.user_role }}
