name: create_mongodb_user
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: Application Name (like 'hc-abc')
        required: true
      env_name:
        description: Environment Name (like 'dev, stage, prod')
        required: true
      db_name:
        description: Database Name (alphanumeric with _ only, casesensitive)
        required: true
      user_name:
        description: User Name (alphanumeric with _ only, casesensitive)
        required: true
      user_password:
        description: User Password (alphanumeric with upper, lower and !~-_ only, casesensitive)
        required: true
      user_role:
          description: User Role
          required: true 
          type: choice
          options:
            - readWrite
            - read
          
jobs:
  workflow_dispatch:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Create MongoDB User Workflow
        id: mongodb_user
        run: >-
          echo App Name ${{ github.event.inputs.app_name }}
          echo User Name ${{ github.event.inputs.user_name }}
          echo Role Name ${{ github.event.inputs.user_role }}
          python scripts/mongodb_atlas/mongodb_create_user.py \
           --app_name "${{ github.event.inputs.app_name }}" \
           --db_name "${{ github.event.inputs.db_name }}" \
           --env_name "${{ github.event.inputs.env_name }}" \ 
           --user_name "${{ github.event.inputs.user_name }}" \ 
           --user_password "${{ github.event.inputs.user_password }}" \ 
           --user_role "${{ github.event.inputs.user_role }}" 
          echo User created...

